### ISSUE TITLE
Trying to open a file crashes on Linux

### ISSUE THREAD

**Issue by GoldsteinE** [Kl4rry/simp#11]
```
$ simp  # And then click `Open`

(simp:87934): GLib-GIO-ERROR **: 02:18:27.006: No GSettings schemas are installed on the system
zsh: trace trap (core dumped)  simp
```

I’m on NixOS, package was built from tag 3.0.0 with the following expression:

```nix
(naersk.buildPackage {
  src = "${inputs.simp}";
  nativeBuildInputs = with pkgs; [
    git
    pkg-config
    gtk3
    xorg.libxcb
    speechd
    libxkbcommon
    openssl
  ];
})
```

Opening a file by passing the path as an argument works properly.

**Comment by Kl4rry** [comment]
It seems to be some kind of configuration error maybe the XDG_DATA_DIRS var is set to something weird.

**Comment by GoldsteinE** [comment]
Was a mistake in my derivation.

If I were to contribute `flake.nix` to the repo, would such a PR be accepted? I’m willing to support it.
