### ISSUE TITLE
UI Flickering

### ISSUE THREAD

**Issue by nothke** [Kl4rry/simp#12]
On Windows, there's some crazy flickering of the UI and font skewing going on:

![flickeringf](https://user-images.githubusercontent.com/5682833/187416777-740e247d-1033-47d6-9bed-10a281d9e6c5.gif)

**Comment by Kl4rry** [comment]
That is very odd. Does it happen all of the time or does it require some sepcific action to reproduce? I have never experienced something similar.

**Comment by wwwxkz** [comment]
If you look closely you can see that is the same issue, I do not why but it happens often when obs is not recording 
![flickering](https://user-images.githubusercontent.com/44681621/187932803-203a5e41-9477-4408-9d62-1444d454633a.gif)

**Comment by Kl4rry** [comment]
The question is if the problem is caused by me, or by egui or by the GPU driver.

**Comment by Kl4rry** [comment]
Likely fix by port to wgpu.
