### ISSUE TITLE
Picture should resize when maximizing window / going fullscreen

### ISSUE THREAD

**Issue by olivier-fs** [Kl4rry/simp#14]
Hi!

When maximizing the window or going fullscreen (F11 on Windows), the picture is not resized.
I think the default behavior should be maximizing (MS Paint does this)

Thank you for this nice tool !
I dumped MS Paint as image viewer : even if Paint is quite fast, it can't compete with a lightweight rust executable ;-)
Great use of egui, I'm gonna look at the code as soon as I have free time.

**Comment by Kl4rry** [comment]
Should be pretty easy to implement. If you wanna draft a pr take a look at the `best_fit` and `largest_fit` functions.

**Comment by olivier-fs** [comment]
best_fit() is perfect. Just adding one liner self.best_fit() in WindowEvent::Resized event handler works great : very smooth, very fast, no flicker at all, even on an XPS 13 with no fancy GeForce/Radeon, only integrated Intel GPU. glium is fast at computing pixels and egui at dispatching events.

Resizing only on mouse button release would require tracking the button state with a mouse_button_pressed: bool.
I'm neither winit nor egui specialist, but from what I understand there is no WindowEvent::Maximized event. So WindowEvent::Resized is the only way to go. 

Resizing only on button release would require tracking the mouse button state with a mouse_button_pressed: bool attribute in App, but I've only found WindowEvent::MouseInput, and this event is dispatched only on button release, not button click, so it's not useful for tracking the state, only for reacting to click "command".

I should really find free time to learn winit and egui.

**Comment by olivier-fs** [comment]
largest_fit() is the one.
As implied by the name : does not depend on the image size related to the window size.

app.rs / handle_window_event()
```rust
            WindowEvent::Resized(size) => {
                *self.size.mut_x() = size.width as f32;
                *self.size.mut_y() = size.height as f32;

                self.largest_fit();
            }
```

**Comment by olivier-fs** [comment]
What would be really cool (while still keep simp _simple_) :
- Menu entries as radio buttons (or some other selectable item) for resize mode
- A status bar item displaying the current resize mode

The easy part:
- Adding ResizeMode enum and a resize_mode attribute in App
```rust
enum ResizeMode {
    Original,
    BestFit,
    LargestFit,
}

pub struct App {
    exit: Arc<AtomicBool>,
    delay: Option<Duration>,
    pub image_view: Option<Box<ImageView>>,
    pub size: Vec2<f32>,
    fullscreen: bool,
    pub top_bar_size: f32,
    pub bottom_bar_size: f32,
    proxy: EventLoopProxy<UserEvent>,
    modifiers: ModifiersState,
    mouse_position: Vec2<f32>,
    current_filename: String,
    op_queue: OpQueue,
    resize: Resize,
    help_visible: bool,
    color_visible: bool,
    metadata_visible: bool,

    resize_mode: ResizeMode,
}
```
- Changing the resize mode in WindowEvent::KeyboardInput
```rust
                        VirtualKeyCode::L => {
                            self.resize_mode = ResizeMode::LargestFit;
                            self.largest_fit();
                        }
                        VirtualKeyCode::B => {
                            self.resize_mode = ResizeMode::BestFit;
                            self.best_fit();
                        }
```
- Matching resize_mode in WindowEvent::Resized
```rust
            WindowEvent::Resized(size) => {
                *self.size.mut_x() = size.width as f32;
                *self.size.mut_y() = size.height as f32;

                match self.resize_mode {
                    ResizeMode::Original => {},
                    ResizeMode::LargestFit => { self.largest_fit(); },
                    ResizeMode::BestFit => { self.best_fit(); },
                }

            }
```

The hard part (for me) : menu entries and status bar span.

I have to improve my egui kungfu. I know MFC, Qt and GTK, but I actually know quite nothing about the (great IMHO from what I see) egui crate...
I will read your code and try to add these, but I'll probably be slow, and you may finish coding this way before me.

**Comment by Kl4rry** [comment]
The resizing mode idea is interesting and I will have to check it out myself. But as a first step a suggest calling the resizing function in the code that handles fullscreening.
```
VirtualKeyCode::F11 | VirtualKeyCode::F => {
    let window_context = display.gl_window();
    let window = window_context.window();
    let fullscreen = window.fullscreen();
    if fullscreen.is_some() {
        window.set_fullscreen(None);
        self.fullscreen = false;
        self.top_bar_size = TOP_BAR_SIZE;
        self.bottom_bar_size = BOTTOM_BAR_SIZE;
    } else {
        window.set_fullscreen(Some(Fullscreen::Borderless(None)));
        self.fullscreen = true;
        self.top_bar_size = 0.0;
        self.bottom_bar_size = 0.0;
    }
}
```
