### ISSUE TITLE
Usability: Hide invalid file types in file picker

### ISSUE THREAD

**Issue by DannyJJK** [Kl4rry/simp#20]
It would be nice for the file picker to only allow selecting image files that are supportred by Simp.

I mainly work in webdev so I know In HTML you can create a file picker that is limited to certain files like this:
`<input type="file" accept="image/*">`

On Windows, this hides non-image files. On macOS, this grays them out and doesn't allow them to be selected. And I imagine Linux distros do one of those two things.

I imagine there should be an option to provide this when creating the file picker, but if not then maybe this is a feature suggestion for the GUI framework.

**Comment by Kl4rry** [comment]
It is very easy to add filters to the file picker. The only issue is that it is not possible to hide the options so it looks quite ridiculous on windows.
![bild](https://user-images.githubusercontent.com/69117984/203113840-d0cf737e-6645-4244-acd4-51de982fbee3.png)

**Comment by Kl4rry** [comment]
But that is a separate problem.
