### ISSUE TITLE
Glium egui deprecation

### ISSUE THREAD

**Issue by Kl4rry** [Kl4rry/simp#22]
Simp uses egui glium which is now deprecated and no longer updated. What do?

**Comment by 0323pin** [comment]
@Kl4rry Could this help, https://github.com/fayalalebrun/egui_glium ?
Found it while browsing crates.io and remembered this issue.

**Comment by Kl4rry** [comment]
Yes it's very helpfull as now don't have to do the patching of egui glium myself.

**Comment by Kl4rry** [comment]
Fixed by porting to wgpu.
