### ISSUE TITLE
vim style keys

### ISSUE THREAD

**Issue by badwatt** [Kl4rry/simp#23]
It would be awesome to add support for vim keys.

**Comment by Kl4rry** [comment]
Could you be more specific on how vim keys would work in a image editor? Vim keybinds are designed for a text editor and it's not trival to map them into a image editor. Do you just mean the simple things like moving around with hjkl or do you mean that every editing  operation is supported using different editing modes?

**Comment by badwatt** [comment]
I think just for moving between (hjkl) would be fine.

**Comment by Kl4rry** [comment]
Do you mean moving like looking at a different part of the image or do you mean having the same behavior as the arrow keys which is going to the next image in the directory?

**Comment by badwatt** [comment]
Same functionality as the arrow keys 🙏

**Comment by Kl4rry** [comment]
Added in ad9c05a4946e6f3c84f39c3e1bb104f449fbc681
