### ISSUE TITLE
error decoding image: "from stdin"

### ISSUE THREAD

**Issue by piotrbajdek** [Kl4rry/simp#29]
Hi, I'm using Fedora Linux 39. In Simp 3.5.2, I encounter the following error message upon startup:

`error decoding image: "from stdin"`

This issue does not occur in the previous version of the program, 3.5.1.

[![Screenshot-from-2024-03-10-19-00-23.png](https://i.postimg.cc/vDR2mmGm/Screenshot-from-2024-03-10-19-00-23.png)](https://postimg.cc/Pv4Q3TpG)

**Comment by Kl4rry** [comment]
How are you starting it? Command line or from a launcher?

**Comment by piotrbajdek** [comment]
> How are you starting it? Command line or from a launcher?

I was launching the program from the launcher, i.e., by clicking the icon. I checked this out, and it turns out that this issue doesn't occur when starting it from the command line.

**Comment by Kl4rry** [comment]
adbe240d0e64dba627f046eedda51cea9a2ac2c1 Could you try this commit?

**Comment by piotrbajdek** [comment]
> [adbe240](https://github.com/Kl4rry/simp/commit/adbe240d0e64dba627f046eedda51cea9a2ac2c1) Could you try this commit?

I've compiled the new code. The issue no longer occurs. Thanks for your help!
