### ISSUE TITLE
(Design suggestion) Migrate the UI to egui

### ISSUE THREAD

**Issue by hardBSDk** [Kl4rry/simp#30]
It will remove most C/C++ dependencies on your program.

**Comment by Kl4rry** [comment]
Egui is already used. All C/C++ dependencies are on image decoders.

**Comment by hardBSDk** [comment]
@Kl4rry What about the GTK3 on the README?

**Comment by Kl4rry** [comment]
I think that may just be a documentation error. I think I had a dependency on GTK3 but removed it.

**Comment by hardBSDk** [comment]
@Kl4rry Thanks for the clarification, please update the system dependencies on the README.
