### ISSUE TITLE
Image in fullscreen mode should be 100% zoom

### ISSUE THREAD

**Issue by chillinbythetree** [Kl4rry/simp#37]
The current zoom is not at 100% by default in fullscreen mode, so there's grey padding around the image even if the image is the size of the screen resolution. For example, my wallpaper (1920 x 1080) should be taking up the whole screen (1920 x 1080) in the screenshot attached. The default zoom in fullscreen mode should be 100%.

![20240629_07h56m52s_grim](https://github.com/Kl4rry/simp/assets/141879625/1d97bb3b-038f-489c-a25d-bf5282ebedf9)

**Comment by Kl4rry** [comment]
Fixed in  4f3d64a877afdafc4868e1f9af83557c81623380.
