### ISSUE TITLE
error[E0658]: use of unstable library feature 'lazy_cell'

### ISSUE THREAD

**Issue by chillinbythetree** [Kl4rry/simp#41]
Just cloned the repo and ran "cargo build". It fails to build due to "error[E0658]: use of unstable library feature 'lazy_cell'". Here is the full log:

   Compiling simp v3.6.1 (/home/gir/Code/rust/projects/simp)
error[E0658]: use of unstable library feature 'lazy_cell'
 --> src/util/extensions.rs:1:5
  |
1 | use std::sync::LazyLock;
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
 --> src/util/extensions.rs:3:17
  |
3 | pub static JXL: LazyLock<&[&'static str]> = LazyLock::new(|| &["jxl"]);
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
 --> src/util/extensions.rs:3:45
  |
3 | pub static JXL: LazyLock<&[&'static str]> = LazyLock::new(|| &["jxl"]);
  |                                             ^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
 --> src/util/extensions.rs:5:18
  |
5 | pub static HEIF: LazyLock<&[&'static str]> = LazyLock::new(|| &["heif", "heic"]);
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
 --> src/util/extensions.rs:5:46
  |
5 | pub static HEIF: LazyLock<&[&'static str]> = LazyLock::new(|| &["heif", "heic"]);
  |                                              ^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
 --> src/util/extensions.rs:7:20
  |
7 | pub static RASTER: LazyLock<&[&'static str]> = LazyLock::new(|| {
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
 --> src/util/extensions.rs:7:48
  |
7 | pub static RASTER: LazyLock<&[&'static str]> = LazyLock::new(|| {
  |                                                ^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:14:33
   |
14 | pub static UNDETECTABLE_RASTER: LazyLock<&[&'static str]> = LazyLock::new(|| &["tga"]);
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:14:61
   |
14 | pub static UNDETECTABLE_RASTER: LazyLock<&[&'static str]> = LazyLock::new(|| &["tga"]);
   |                                                             ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:16:20
   |
16 | pub static VECTOR: LazyLock<&[&'static str]> = LazyLock::new(|| &["svg"]);
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:16:48
   |
16 | pub static VECTOR: LazyLock<&[&'static str]> = LazyLock::new(|| &["svg"]);
   |                                                ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:18:17
   |
18 | pub static RAW: LazyLock<&[&'static str]> = LazyLock::new(|| {
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:18:45
   |
18 | pub static RAW: LazyLock<&[&'static str]> = LazyLock::new(|| {
   |                                             ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:25:23
   |
25 | pub static PHOTOSHOP: LazyLock<&[&'static str]> = LazyLock::new(|| &["psd"]);
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:25:51
   |
25 | pub static PHOTOSHOP: LazyLock<&[&'static str]> = LazyLock::new(|| &["psd"]);
   |                                                   ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:27:24
   |
27 | pub static EXTENSIONS: LazyLock<Vec<&'static str>> = LazyLock::new(|| {
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:27:54
   |
27 | pub static EXTENSIONS: LazyLock<Vec<&'static str>> = LazyLock::new(|| {
   |                                                      ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
 --> src/util/extensions.rs:3:45
  |
3 | pub static JXL: LazyLock<&[&'static str]> = LazyLock::new(|| &["jxl"]);
  |                                             ^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
 --> src/util/extensions.rs:5:46
  |
5 | pub static HEIF: LazyLock<&[&'static str]> = LazyLock::new(|| &["heif", "heic"]);
  |                                              ^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
 --> src/util/extensions.rs:7:48
  |
7 | pub static RASTER: LazyLock<&[&'static str]> = LazyLock::new(|| {
  |                                                ^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:14:61
   |
14 | pub static UNDETECTABLE_RASTER: LazyLock<&[&'static str]> = LazyLock::new(|| &["tga"]);
   |                                                             ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:16:48
   |
16 | pub static VECTOR: LazyLock<&[&'static str]> = LazyLock::new(|| &["svg"]);
   |                                                ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:18:45
   |
18 | pub static RAW: LazyLock<&[&'static str]> = LazyLock::new(|| {
   |                                             ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:25:51
   |
25 | pub static PHOTOSHOP: LazyLock<&[&'static str]> = LazyLock::new(|| &["psd"]);
   |                                                   ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/util/extensions.rs:27:54
   |
27 | pub static EXTENSIONS: LazyLock<Vec<&'static str>> = LazyLock::new(|| {
   |                                                      ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `simp` (bin "simp") due to 25 previous errors

**Comment by Kl4rry** [comment]
Update your compiler. Simp only supports the most recent rust compiler.

**Comment by chillinbythetree** [comment]
> Update your compiler. Simp only supports the most recent rust compiler.

Yup, that was it. Used the latest update from the OS but it was at 1.79 and not the latest 1.80 release. Changed repository and now it builds. Thanks.
